extern crate bindgen;

use std::env;
use std::fs;
use std::path::{PathBuf};

fn main() {
  let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
  let cuda_dir = PathBuf::from(match env::var("CUDA_HOME") {
    Ok(path) => path,
    Err(_) => "/usr/local/cuda".to_owned(),
  });
  let cudnn_dir = match env::var("CUDNN_HOME") {
    Ok(path) => PathBuf::from(path),
    Err(_) => cuda_dir.clone(),
  };

  println!("cargo:rustc-link-lib=cudnn");

  let cudnn_bindings = bindgen::Builder::default()
    .clang_arg(format!("-I{}", cudnn_dir.join("include").as_os_str().to_str().unwrap()))
    .clang_arg(format!("-I{}", cuda_dir.join("include").as_os_str().to_str().unwrap()))
    .header("wrap.h")
    //.link("cudnn")
    .whitelist_recursively(false)
    .whitelist_var("CUDNN_MAJOR")
    .whitelist_var("CUDNN_MINOR")
    .whitelist_var("CUDNN_PATCHLEVEL")
    .whitelist_var("CUDNN_DIM_MAX")
    .whitelist_type("cudnnContext")
    .whitelist_type("cudnnHandle_t")
    .whitelist_type("cudnnStatus_t")
    .whitelist_function("cudnnGetVersion")
    .whitelist_function("cudnnGetErrorString")
    .whitelist_function("cudnnCreate")
    .whitelist_function("cudnnDestroy")
    .whitelist_function("cudnnSetStream")
    .whitelist_function("cudnnGetStream")
    .whitelist_type("cudnnTensorStruct")
    .whitelist_type("cudnnTensorDescriptor_t")
    .whitelist_type("cudnnTensorFormat_t")
    .whitelist_type("cudnnConvolutionStruct")
    .whitelist_type("cudnnConvolutionDescriptor_t")
    .whitelist_type("cudnnPoolingStruct")
    .whitelist_type("cudnnPoolingDescriptor_t")
    .whitelist_type("cudnnFilterStruct")
    .whitelist_type("cudnnFilterDescriptor_t")
    .whitelist_type("cudnnActivationStruct")
    .whitelist_type("cudnnActivationDescriptor_t")
    .whitelist_type("cudnnOpTensorStruct")
    .whitelist_type("cudnnOpTensorDescriptor_t")
    .whitelist_type("cudnnReduceTensorStruct")
    .whitelist_type("cudnnReduceTensorDescriptor_t")
    .whitelist_type("cudnnDataType_t")
    .whitelist_type("cudnnMathType_t")
    .whitelist_type("cudnnNanPropagation_t")
    .whitelist_type("cudnnDeterminism_t")
    .whitelist_function("cudnnCreateTensorDescriptor")
    .whitelist_type("cudnnTensorFormat_t")
    .whitelist_function("cudnnSetTensor4dDescriptor")
    .whitelist_function("cudnnSetTensor4dDescriptorEx")
    .whitelist_function("cudnnGetTensor4dDescriptor")
    .whitelist_function("cudnnSetTensorNdDescriptor")
    .whitelist_function("cudnnSetTensorNdDescriptorEx")
    .whitelist_function("cudnnGetTensorNdDescriptor")
    .whitelist_function("cudnnGetTensorSizeInBytes")
    .whitelist_function("cudnnDestroyTensorDescriptor")
    .whitelist_function("cudnnTransformTensor")
    .whitelist_function("cudnnAddTensor")
    .whitelist_function("cudnnSetTensor")
    .whitelist_function("cudnnScaleTensor")
    .whitelist_type("cudnnOpTensorOp_t")
    .whitelist_function("cudnnCreateOpTensorDescriptor")
    .whitelist_function("cudnnSetOpTensorDescriptor")
    .whitelist_function("cudnnGetOpTensorDescriptor")
    .whitelist_function("cudnnDestroyOpTensorDescriptor")
    .whitelist_function("cudnnOpTensor")
    .whitelist_type("cudnnReduceTensorOp_t")
    .whitelist_type("cudnnReduceTensorIndices_t")
    .whitelist_type("cudnnIndicesType_t")
    .whitelist_function("cudnnCreateReduceTensorDescriptor")
    .whitelist_function("cudnnSetReduceTensorDescriptor")
    .whitelist_function("cudnnGetReduceTensorDescriptor")
    .whitelist_function("cudnnDestroyReduceTensorDescriptor")
    .whitelist_function("cudnnGetReductionIndicesSize")
    .whitelist_function("cudnnGetReductionWorkspaceSize")
    .whitelist_function("cudnnReduceTensor")
    .whitelist_type("cudnnConvolutionMode_t")
    .whitelist_function("cudnnCreateFilterDescriptor")
    .whitelist_function("cudnnSetFilter4dDescriptor")
    .whitelist_function("cudnnGetFilter4dDescriptor")
    .whitelist_function("cudnnSetFilterNdDescriptor")
    .whitelist_function("cudnnGetFilterNdDescriptor")
    .whitelist_function("cudnnDestroyFilterDescriptor")
    .whitelist_function("cudnnCreateConvolutionDescriptor")
    .whitelist_function("cudnnSetConvolutionMathType")
    .whitelist_function("cudnnGetConvolutionMathType")
    .whitelist_function("cudnnSetConvolutionGroupCount")
    .whitelist_function("cudnnGetConvolutionGroupCount")
    .whitelist_function("cudnnSetConvolution2dDescriptor")
    .whitelist_function("cudnnGetConvolution2dDescriptor")
    .whitelist_function("cudnnGetConvolution2dForwardOutputDim")
    .whitelist_function("cudnnSetConvolutionNdDescriptor")
    .whitelist_function("cudnnGetConvolutionNdDescriptor")
    .whitelist_function("cudnnGetConvolutionNdForwardOutputDim")
    .whitelist_function("cudnnDestroyConvolutionDescriptor")
    .whitelist_type("cudnnConvolutionFwdPreference_t")
    .whitelist_type("cudnnConvolutionFwdAlgo_t")
    .whitelist_type("cudnnConvolutionFwdAlgoPerf_t")
    .whitelist_function("cudnnGetConvolutionForwardAlgorithmMaxCount")
    .whitelist_function("cudnnFindConvolutionForwardAlgorithm")
    .whitelist_function("cudnnFindConvolutionForwardAlgorithmEx")
    .whitelist_function("cudnnGetConvolutionForwardAlgorithm")
    .whitelist_function("cudnnGetConvolutionForwardAlgorithm_v7")
    .whitelist_function("cudnnGetConvolutionForwardWorkspaceSize")
    .whitelist_function("cudnnConvolutionForward")
    .whitelist_function("cudnnConvolutionBackwardBias")
    .whitelist_type("cudnnConvolutionBwdFilterPreference_t")
    .whitelist_type("cudnnConvolutionBwdFilterAlgo_t")
    .whitelist_type("cudnnConvolutionBwdFilterAlgoPerf_t")
    .whitelist_function("cudnnGetConvolutionBackwardFilterAlgorithmMaxCount")
    .whitelist_function("cudnnFindConvolutionBackwardFilterAlgorithm")
    .whitelist_function("cudnnFindConvolutionBackwardFilterAlgorithmEx")
    .whitelist_function("cudnnGetConvolutionBackwardFilterAlgorithm")
    .whitelist_function("cudnnGetConvolutionBackwardFilterAlgorithm_v7")
    .whitelist_function("cudnnGetConvolutionBackwardFilterWorkspaceSize")
    .whitelist_function("cudnnConvolutionBackwardFilter")
    .whitelist_type("cudnnConvolutionBwdDataPreference_t")
    .whitelist_type("cudnnConvolutionBwdDataAlgo_t")
    .whitelist_type("cudnnConvolutionBwdDataAlgoPerf_t")
    .whitelist_function("cudnnGetConvolutionBackwardDataAlgorithmMaxCount")
    .whitelist_function("cudnnFindConvolutionBackwardDataAlgorithm")
    .whitelist_function("cudnnFindConvolutionBackwardDataAlgorithmEx")
    .whitelist_function("cudnnGetConvolutionBackwardDataAlgorithm")
    .whitelist_function("cudnnGetConvolutionBackwardDataAlgorithm_v7")
    .whitelist_function("cudnnGetConvolutionBackwardDataWorkspaceSize")
    .whitelist_function("cudnnConvolutionBackwardData")
    .whitelist_type("cudnnSoftmaxAlgorithm_t")
    .whitelist_type("cudnnSoftmaxMode_t")
    .whitelist_function("cudnnSoftmaxForward")
    .whitelist_function("cudnnSoftmaxBackward")
    .whitelist_type("cudnnPoolingMode_t")
    .whitelist_function("cudnnCreatePoolingDescriptor")
    .whitelist_function("cudnnSetPooling2dDescriptor")
    .whitelist_function("cudnnGetPooling2dDescriptor")
    .whitelist_function("cudnnSetPoolingNdDescriptor")
    .whitelist_function("cudnnGetPoolingNdDescriptor")
    .whitelist_function("cudnnDestroyPoolingDescriptor")
    .whitelist_function("cudnnPoolingForward")
    .whitelist_function("cudnnPoolingBackward")
    .whitelist_type("cudnnActivationMode_t")
    .whitelist_function("cudnnCreateActivationDescriptor")
    .whitelist_function("cudnnSetActivationDescriptor")
    .whitelist_function("cudnnGetActivationDescriptor")
    .whitelist_function("cudnnDestroyActivationDescriptor")
    .whitelist_function("cudnnActivationForward")
    .whitelist_function("cudnnActivationBackward")
    .whitelist_type("cudnnBatchNormMode_t")
    .whitelist_function("cudnnDeriveBNTensorDescriptor")
    .whitelist_function("cudnnBatchNormalizationForwardTraining")
    .whitelist_function("cudnnBatchNormalizationForwardInference")
    .whitelist_function("cudnnBatchNormalizationBackward")
    .whitelist_type("cudnnDropoutStruct")
    .whitelist_type("cudnnDropoutDescriptor_t")
    .whitelist_function("cudnnCreateDropoutDescriptor")
    .whitelist_function("cudnnDestroyDropoutDescriptor")
    .whitelist_function("cudnnDropoutGetStateSpaceSize")
    .whitelist_function("cudnnDropoutGetReserveSpaceSize")
    .whitelist_function("cudnnSetDropoutDescriptor")
    .whitelist_function("cudnnRestoreDropoutDescriptor")
    .whitelist_function("cudnnGetDropoutDescriptor")
    .whitelist_function("cudnnDropoutForward")
    .whitelist_function("cudnnDropoutBackward")
    .generate()
    .expect("bindgen failed to generate cudnn bindings");
  fs::remove_file(out_dir.join("cudnn_bind.rs")).ok();
  cudnn_bindings
    .write_to_file(out_dir.join("cudnn_bind.rs"))
    .expect("bindgen failed to write cudnn bindings");
}
